inherit_from: .rubocop_todo.yml
inherit_gem:
  ruboconfig: rubocop.yml

AllCops:
  TargetRubyVersion: 2.4

# Limit lines to 80 characters.
LineLength:
  Max: 80

ClassLength:
  Max: 400

# Avoid single-line methods.
SingleLineMethods:
  AllowIfMethodIsEmpty: true

# Wants underscores in all large numbers. Pain in the ass for things like
# unix timestamps.
NumericLiterals:
  Enabled: false

Performance/RegexpMatch:
  Enabled: false

# Wants you to use the same argument names for every reduce. This seems kinda
# naff compared to naming them semantically
SingleLineBlockParams:
  Enabled: false

Style/SignalException:
  EnforcedStyle: 'only_raise'

# Wants to exclude accents from comments
Style/AsciiComments:
  Enabled: false

# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 25

# Configuration parameters: CountComments.
Metrics/ModuleLength:
  Max: 400

Layout/DotPosition:
  EnforcedStyle: 'trailing'
