language: ruby

matrix:
  allow_failures:
    - rvm: jruby
    - rvm: rbx-2

rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - jruby
  - rbx-2

sudo: false

script:
  - bundle exec rubocop
  - bundle exec rspec spec
