language: ruby

matrix:
  allow_failures:

rvm:
  - 2.1.10
  - 2.2.7
  - 2.3.4
  - 2.4.1

sudo: false

before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'

script:
  - bundle exec rubocop
  - bundle exec rspec spec
