module Ibandit
  module Constants
    CONSTRUCTABLE_IBAN_COUNTRY_CODES = %w[AT BE BG CY CZ DE DK EE ES FI FR GB GR
                                          HR HU IE IS IT LT LU LV MC MT NL NO PL
                                          PT RO SE SI SK SM].freeze

    PSEUDO_IBAN_COUNTRY_CODES = %w[AU SE].freeze
    DECONSTRUCTABLE_IBAN_COUNTRY_CODES =
      CONSTRUCTABLE_IBAN_COUNTRY_CODES - PSEUDO_IBAN_COUNTRY_CODES

    PSEUDO_IBAN_CHECK_DIGITS = "ZZ".freeze

    SUPPORTED_COUNTRY_CODES = (
      CONSTRUCTABLE_IBAN_COUNTRY_CODES +
      DECONSTRUCTABLE_IBAN_COUNTRY_CODES +
      PSEUDO_IBAN_COUNTRY_CODES
    ).uniq
  end
end
